import Head from "next/head";
import { Header } from "./header";

type HeaderProps = {
  children: React.ReactNode;
};

export function LayoutMain({ children }: HeaderProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>{children}</main>
    </div>
  );
}
